apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: punitacr.azurecr.io/goproj
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-enable-tcp-reset: "true"
    service.beta.kubernetes.io/azure-load-balancer-preserve-client-ip: "true"
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

